"""Add mission launch site and change description type

Revision ID: 2c420b279c06
Revises: 927a43e0c1e3
Create Date: 2026-07-21 13:35:05.378624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c420b279c06'
down_revision: Union[str, Sequence[str], None] = '927a43e0c1e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('missions', sa.Column('launch_site', sa.String(length=255), nullable=True))
    op.alter_column('missions', 'description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('missions', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_column('missions', 'launch_site')
    # ### end Alembic commands ###
