"""Create chat response cache model

Revision ID: 2f7844efd646
Revises: 39afccad9443
Create Date: 2026-08-01 11:29:24.988603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f7844efd646'
down_revision: Union[str, Sequence[str], None] = '39afccad9443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_response_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_response_cache', 'last_hit_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('chat_cache_embedding_idx'), table_name='chat_response_cache', postgresql_ops={'question_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('chat_cache_embedding_idx'), 'chat_response_cache', ['question_embedding'], unique=False, postgresql_ops={'question_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('chat_response_cache', 'last_hit_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_response_cache', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
