"""Add content hash to chunk table

Revision ID: 39afccad9443
Revises: 45260600bde7
Create Date: 2026-07-31 14:00:34.535496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39afccad9443'
down_revision: Union[str, Sequence[str], None] = '45260600bde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('content_hash', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'content_hash')
    # ### end Alembic commands ###
