"""Add fields to structure

Revision ID: 3af99e9971ba
Revises: d241726a0350
Create Date: 2026-07-22 17:08:42.621536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3af99e9971ba'
down_revision: Union[str, Sequence[str], None] = 'd241726a0350'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('eccentricity', sa.Float(), nullable=True))
    op.add_column('structures', sa.Column('semimajoraxis', sa.Float(), nullable=True))
    op.add_column('structures', sa.Column('inclination', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'inclination')
    op.drop_column('structures', 'semimajoraxis')
    op.drop_column('structures', 'eccentricity')
    # ### end Alembic commands ###
