"""Add fields to Structure

Revision ID: 51e9b4124c78
Revises: 6b563de88d33
Create Date: 2026-07-18 16:34:13.418189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e9b4124c78'
down_revision: Union[str, Sequence[str], None] = '6b563de88d33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('type_planet', sa.String(length=100), nullable=True))
    op.add_column('structures', sa.Column('glow', sa.String(length=100), nullable=True))
    op.add_column('structures', sa.Column('tagline', sa.String(length=255), nullable=True))
    op.add_column('structures', sa.Column('fact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'fact')
    op.drop_column('structures', 'tagline')
    op.drop_column('structures', 'glow')
    op.drop_column('structures', 'type_planet')
    # ### end Alembic commands ###
