"""Update Structure

Revision ID: 5467138b68c2
Revises: 5d20da98da6f
Create Date: 2026-07-17 11:26:00.445238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5467138b68c2'
down_revision: Union[str, Sequence[str], None] = '5d20da98da6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('escape', sa.Float(), nullable=True))
    op.add_column('structures', sa.Column('period', sa.Float(), nullable=True))
    op.drop_column('structures', 'mass')
    op.drop_column('structures', 'volume')
    op.add_column('structures', sa.Column('mass', sa.JSON(), nullable=True))
    op.add_column('structures', sa.Column('volume', sa.JSON(), nullable=True))
    op.drop_column('structures', 'escape_velocity')
    op.drop_column('structures', 'orbital_period')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('orbital_period', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('structures', sa.Column('escape_velocity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('structures', 'volume',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('structures', 'mass',
               existing_type=sa.JSON(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('structures', 'period')
    op.drop_column('structures', 'escape')
    # ### end Alembic commands ###
