"""Add inital long for planets

Revision ID: 5e1d0a1b7351
Revises: 3af99e9971ba
Create Date: 2026-07-22 21:38:20.922862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e1d0a1b7351'
down_revision: Union[str, Sequence[str], None] = '3af99e9971ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('long', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'long')
    # ### end Alembic commands ###
