"""Add image_url to structures

Revision ID: 6b563de88d33
Revises: 5467138b68c2
Create Date: 2026-07-18 14:10:27.808966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b563de88d33'
down_revision: Union[str, Sequence[str], None] = '5467138b68c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'image_url')
    # ### end Alembic commands ###
