"""Add radius to structures model

Revision ID: aacbb207dd4f
Revises: 5e1d0a1b7351
Create Date: 2026-07-26 16:03:52.693895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aacbb207dd4f'
down_revision: Union[str, Sequence[str], None] = '5e1d0a1b7351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('structures', sa.Column('radius', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('structures', 'radius')
    # ### end Alembic commands ###
