"""Add path and type of response to chatResponseCache

Revision ID: f101e3860e44
Revises: 2f7844efd646
Create Date: 2026-08-05 15:52:05.181681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f101e3860e44'
down_revision: Union[str, Sequence[str], None] = '2f7844efd646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_response_cache', sa.Column('type_of_response', sa.String(length=255), nullable=False))
    op.add_column('chat_response_cache', sa.Column('path', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_response_cache', 'path')
    op.drop_column('chat_response_cache', 'type_of_response')
    # ### end Alembic commands ###
